behaviors:
  ALJV:
    trainer_type: ppo
    keep_checkpoints: 100
    checkpoint_interval: 1000000
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1
      gail:
        strength: 0.8
        demo_path: config/TrapsDemos/TrapsDemo.demo
    behavioral_cloning:
      strength: 0.5
      demo_path: config/TrapsDemos/TrapsDemo.demo
    keep_checkpoints: 5
    max_steps: 30000000
    time_horizon: 1000
    summary_freq: 50000
